# Every field in a theme file is optional.

shadow = false
borders = "none"

[colors]
  background         = "black"
  view               = "black"
  primary            = "#eeeeee"
  secondary          = "#dddddd"
  tertiary           = "#cccccc"
  title_primary      = "blue"
  title_secondary    = "yellow"
  highlight          = "green"
  highlight_inactive = "magenta"
